### ISSUE TITLE
Freebsd Support for Other Memory Address methods and Queue types in GVNIC

### ISSUE THREAD

**Issue by ccater** [GoogleCloudPlatform/compute-virtual-ethernet-freebsd#2]
Is there any intention or plans of adding the newer queuing/memory addressing code for gvnic to the Freebsd Driver? 

Specifically Raw Memory Addressing and DQO ?

**Comment by shailend-g** [comment]
Hi ccater, I have just updated this tree to include the recently upstreamed support for DQO-RDA and DQO-QPL. These new datapaths allow making optimal use of NIC bandwidth on gen3 GCP vm shapes.
